# Generated by Django 4.2.1 on 2023-09-04 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
