# Generated by Django 4.2.4 on 2023-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(null=True)),
                ("attatched_file", models.FileField(null=True, upload_to="resources")),
                ("filename", models.TextField(max_length=50)),
            ],
        ),
    ]
