# Generated by Django 4.2.4 on 2023-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="isServer",
            field=models.BooleanField(default=False),
        ),
    ]
